  development:
    adapter: postgresql
    encoding: unicode
    database: auction_development
    pool: 5
    timeout: 5000
    host: localhost
    port:  5432
    username: postgres
    password: password

  test:
    adapter: postgresql
    encoding: unicode
    database: auction_test
    pool: 5
    timeout: 5000
    host: localhost
    port:  5432
    username: postgres
    password: password

